name: mtenn
channels:
  - conda-forge
dependencies:
  - pytorch
  - pytorch_geometric
  - pytorch_cluster
  - pytorch_scatter
  - pytorch_sparse
  - numpy
  - h5py
  - e3nn
  - dgllife
  - dgl
  - rdkit
  - ase

  # docs
  - sphinx
  - sphinx_rtd_theme
