name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}


jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}, Env ${{ matrix.deps }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
        deps: ["devtools/conda-envs/test_env.yaml"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Additional info about the build
      run: |
        uname -a
        df -h
        ulimit -a


    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.10-0'
        environment-file: ${{ matrix.deps }}
        environment-name: test
        create-args: >-
          python==${{ matrix.python-version }}

    - name: Install package
      run: |
        python -m pip install . --no-deps
        micromamba list


    - name: Run tests
      run: |
        pytest -v --cov=mtenn --cov-report=xml --color=yes mtenn/tests/

    - name: Upload Code Coverage to Codecov
      uses: codecov/codecov-action@v3
      # Don't upload coverage scheduled or on fork
      if: ${{ github.repository == 'choderalab/mtenn'
              && github.event != 'schedule' }}
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}-env${{ matrix.deps }}
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
